### ISSUE TITLE
OSBMX JLCPCB emailed me about concerns with printing

### ISSUE THREAD

**Issue by spelled-ayayron** [TheTrainGoes/GP2040-Projects#11]
JLCPCB sent me an email regarding an order I placed for 40x of the 30mm OSBMX housings. I've attached a screenshot of the email.

I'm not entirely sure how I should reply to the email since I don't know too much about 3D printing.

![image](https://user-images.githubusercontent.com/10445573/221856954-a488fcc1-c86d-4c14-91b8-dca8ca6ae28d.png)

**Comment by spelled-ayayron** [comment]
I think I'm going to go through with the order as is and take the risk of losing some since I did order 40, but I thought this should be brought to attention in case someone else encounters this.

**Comment by TheTrainGoes** [comment]
If you have not approved already I would ask them if you can replace the file.  I’m going to upload a modified version that should take care of these issues.

**Comment by TheTrainGoes** [comment]
I have updated the main sprue files as well as the individual components.

Sprues now have 1.5mm sizing and the 30mm washer has been increased by 1%.

If possible - please ask JLC to replace the file with the new one I have uploaded

**Comment by spelled-ayayron** [comment]
Thanks, I'll send in the modified file instead!

**Comment by spelled-ayayron** [comment]
Apparently the JLCPCB audit caught some more errors after the update. I've attached screenshots of them again.

![image](https://user-images.githubusercontent.com/10445573/222545673-9196202b-772f-4f20-be80-62b43a543348.png)
![image](https://user-images.githubusercontent.com/10445573/222545764-7215000d-bf6c-4c9a-a09d-963376bcde50.png)

**Comment by TheTrainGoes** [comment]
I would be fine with those.   JLC loves giving error warning.
