### ISSUE TITLE
Issue - 2.4mm not enough spacing between prong sockets

### ISSUE THREAD

**Issue by JarTheHead** [TheTrainGoes/GP2040-Projects#12]
The DJ610-2.8-5 do not fit into the 2.4mm pcb without bending the pins with some pliers. A little bit more space between the two sockets may be needed.

![IMG_2387](https://user-images.githubusercontent.com/24198002/228076195-bc4defb7-9558-4759-8e69-09ebb09f964b.jpg)

**Comment by TheTrainGoes** [comment]
Hi @JarTheHead ,

This version of the board was designed around the vertical 2.4mm prongs.  Unfortunately the only place (which I have found) on AliExpress that sells there has different prong layouts for the vertical and right angle ones that you have here. 

The second issue is that these still require switches with the cutout on them and there is no further room to extend the cutout back into the switch area.  They could be potentially done sideways but that will require a re-design.

**Comment by JarTheHead** [comment]
Oh I see. The Readme has the prongs used listed as the DJ610-2.8-5 (the right angle connector), when I believe it should be the DJ610-2.8-2 that is the vertical prong.
